
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author dhruv
 */
public class CustomerStatus extends javax.swing.JFrame {
  PreparedStatement pst= null; 
    ResultSet rs=null; 
    Connection con=null; 
    
    
    
    
    /**
     * Creates new form customerStatus
     */
    public CustomerStatus() {
        initComponents();
            rateLabel1.setVisible(false);
             discountTypeComboBox.setVisible(false);
             rateTextbox1.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        customerStatusBackground = new javax.swing.JPanel();
        bluePanel = new javax.swing.JPanel();
        customerStatusTitle = new javax.swing.JLabel();
        backButton = new javax.swing.JButton();
        rangeFromLabel = new javax.swing.JLabel();
        rangeToTextbox = new javax.swing.JTextField();
        discountTypeComboBox = new javax.swing.JComboBox<>();
        setStatusComboBox = new javax.swing.JComboBox<>();
        saveButton = new javax.swing.JButton();
        rateLabel1 = new javax.swing.JLabel();
        rangeToLabel = new javax.swing.JLabel();
        rateTextbox1 = new javax.swing.JTextField();
        rangeFromTextbox1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        customerStatusBackground.setBackground(new java.awt.Color(255, 255, 255));
        customerStatusBackground.setPreferredSize(new java.awt.Dimension(1100, 800));

        bluePanel.setBackground(new java.awt.Color(125, 240, 240));

        customerStatusTitle.setFont(new java.awt.Font("Tahoma", 0, 60)); // NOI18N
        customerStatusTitle.setText("CUSTOMER STATUS");

        backButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        backButton.setText("BACK");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonadvisorListActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout bluePanelLayout = new javax.swing.GroupLayout(bluePanel);
        bluePanel.setLayout(bluePanelLayout);
        bluePanelLayout.setHorizontalGroup(
            bluePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bluePanelLayout.createSequentialGroup()
                .addContainerGap(280, Short.MAX_VALUE)
                .addComponent(customerStatusTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 551, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(144, 144, 144)
                .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        bluePanelLayout.setVerticalGroup(
            bluePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bluePanelLayout.createSequentialGroup()
                .addGroup(bluePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bluePanelLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(customerStatusTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(bluePanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(54, Short.MAX_VALUE))
        );

        rangeFromLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        rangeFromLabel.setText("Range From:");

        rangeToTextbox.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        rangeToTextbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rangeToTextboxActionPerformed(evt);
            }
        });

        discountTypeComboBox.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        discountTypeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "DISCOUNT TYPE", "Fixed", "Flexible" }));
        discountTypeComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                discountTypeComboBoxActionPerformed(evt);
            }
        });

        setStatusComboBox.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        setStatusComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SET STATUS", "Regular", "Valued" }));
        setStatusComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setStatusComboBoxActionPerformed(evt);
            }
        });

        saveButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        saveButton.setText("SAVE");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonadvisorListActionPerformed(evt);
            }
        });

        rateLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        rateLabel1.setText("Rate(%):");

        rangeToLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        rangeToLabel.setText(" To:");

        rateTextbox1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        rateTextbox1.setText("enter discount rate...");
        rateTextbox1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rateTextbox1MouseClicked(evt);
            }
        });
        rateTextbox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rateTextbox1ActionPerformed(evt);
            }
        });

        rangeFromTextbox1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        rangeFromTextbox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rangeFromTextbox1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout customerStatusBackgroundLayout = new javax.swing.GroupLayout(customerStatusBackground);
        customerStatusBackground.setLayout(customerStatusBackgroundLayout);
        customerStatusBackgroundLayout.setHorizontalGroup(
            customerStatusBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bluePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(customerStatusBackgroundLayout.createSequentialGroup()
                .addGroup(customerStatusBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, customerStatusBackgroundLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(saveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(customerStatusBackgroundLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(customerStatusBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(customerStatusBackgroundLayout.createSequentialGroup()
                                .addComponent(discountTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(224, 224, 224)
                                .addComponent(rateLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(rateTextbox1, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(customerStatusBackgroundLayout.createSequentialGroup()
                                .addGroup(customerStatusBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(rangeToLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(rangeFromLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(customerStatusBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rangeToTextbox, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(customerStatusBackgroundLayout.createSequentialGroup()
                                        .addComponent(rangeFromTextbox1, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(setStatusComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(54, 54, 54)))
                .addContainerGap())
        );
        customerStatusBackgroundLayout.setVerticalGroup(
            customerStatusBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(customerStatusBackgroundLayout.createSequentialGroup()
                .addComponent(bluePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addGroup(customerStatusBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rangeFromLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rangeFromTextbox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(setStatusComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(customerStatusBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rangeToLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rangeToTextbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(221, 221, 221)
                .addGroup(customerStatusBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(discountTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rateLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rateTextbox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(89, 89, 89)
                .addComponent(saveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(customerStatusBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(customerStatusBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonadvisorListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonadvisorListActionPerformed
        // TODO add your handling code here:
         dispose(); 
    }//GEN-LAST:event_backButtonadvisorListActionPerformed

    private void rangeToTextboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rangeToTextboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rangeToTextboxActionPerformed

    private void discountTypeComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_discountTypeComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_discountTypeComboBoxActionPerformed

    private void setStatusComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setStatusComboBoxActionPerformed
        // TODO add your handling code here:
         int s= setStatusComboBox.getSelectedIndex();
         
              if(s==1){
                 rateLabel1.setVisible(false);
                 discountTypeComboBox.setVisible(false);
                 rateTextbox1.setVisible(false);
              }
              else if(s==2){
              
               rateLabel1.setVisible(true);
                 discountTypeComboBox.setVisible(true);
                 rateTextbox1.setVisible(true);
              
              
              }
    }//GEN-LAST:event_setStatusComboBoxActionPerformed

    private void saveButtonadvisorListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonadvisorListActionPerformed
             // TODO add your handling code here:
      int a= setStatusComboBox.getSelectedIndex();
      
   

    
    
      String fromRange=  rangeFromTextbox1.getText().toString();
         int from= Integer.parseInt(fromRange);
       
       String rangeTo= rangeToTextbox.getText().toString();
        int to= Integer.parseInt(rangeTo);   
        
    try (   Connection con = DbCon.getConnection();) {
  
        
    
       
           
              if(a==1){
   
            PreparedStatement rst = null;
                     rst=con.prepareStatement("UPDATE Customer SET type='regular', discountType =null, discountRate=null WHERE ID IN(SELECT CustomerID FROM Itinerary WHERE FlightNum IN(SELECT number FROM Flights WHERE price>"+from+" and price <"+to+"  ) ) ");
                     rst.execute();
                     JOptionPane.showMessageDialog(null,"regular status assigned");
                     dispose();
              //  System.out.println("set status to reg and nulled discount type and rate"); 
              }
            
            else if(a==2){
              String discountType= discountTypeComboBox.getSelectedItem().toString();
      
           Double discountrate= Double.parseDouble(rateTextbox1.getText());
           PreparedStatement pst =con.prepareStatement("UPDATE Customer SET type='valued', discountType ='"+discountType+"', discountRate='"+discountrate+"' WHERE ID IN(SELECT CustomerID FROM Itinerary WHERE FlightNum IN(SELECT number FROM Flights WHERE price>"+from+" and price <"+to+"  ) ) ");
            pst.execute();
             JOptionPane.showMessageDialog(null," valued status assigned");
              dispose();
              
              }
                
               
          
       
          
         
           
           
      
        }catch (SQLException | ClassNotFoundException e) {
          JOptionPane.showMessageDialog(null,e);
        }
          
 
           
    }//GEN-LAST:event_saveButtonadvisorListActionPerformed

    private void rateTextbox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rateTextbox1ActionPerformed
        // TODO add your handling code here:
      
    }//GEN-LAST:event_rateTextbox1ActionPerformed

    private void rangeFromTextbox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rangeFromTextbox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rangeFromTextbox1ActionPerformed

    private void rateTextbox1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rateTextbox1MouseClicked
        // TODO add your handling code here:
           rateTextbox1.setText("");
    }//GEN-LAST:event_rateTextbox1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CustomerStatus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CustomerStatus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CustomerStatus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustomerStatus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CustomerStatus().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JPanel bluePanel;
    private javax.swing.JPanel customerStatusBackground;
    private javax.swing.JLabel customerStatusTitle;
    private javax.swing.JComboBox<String> discountTypeComboBox;
    private javax.swing.JLabel rangeFromLabel;
    private javax.swing.JTextField rangeFromTextbox1;
    private javax.swing.JLabel rangeToLabel;
    private javax.swing.JTextField rangeToTextbox;
    private javax.swing.JLabel rateLabel1;
    private javax.swing.JTextField rateTextbox1;
    private javax.swing.JButton saveButton;
    private javax.swing.JComboBox<String> setStatusComboBox;
    // End of variables declaration//GEN-END:variables
}
