
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author xahna
 */
public class CustomerForm extends javax.swing.JFrame {
      PreparedStatement pst= null; 
    ResultSet rs=null; 
   
    /**
     * Creates new form createCustomerForm
     */
    public CustomerForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        createCustomerBackground = new javax.swing.JPanel();
        createCustomerBlueBackground = new javax.swing.JPanel();
        createCustomerTitle = new javax.swing.JLabel();
        backButton = new javax.swing.JButton();
        addButton = new javax.swing.JButton();
        emailLabel = new javax.swing.JLabel();
        surnameTextbox = new javax.swing.JTextField();
        firstNameLabel = new javax.swing.JLabel();
        addressLabel = new javax.swing.JLabel();
        dateLabel3 = new javax.swing.JLabel();
        phoneNumberLabel = new javax.swing.JLabel();
        firstNameTextbox = new javax.swing.JTextField();
        emailTextbox = new javax.swing.JTextField();
        addressTextbox = new javax.swing.JTextField();
        phoneNumberTextbox = new javax.swing.JTextField();
        addButton1 = new javax.swing.JButton();
        addButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        createCustomerBackground.setBackground(new java.awt.Color(255, 255, 255));
        createCustomerBackground.setPreferredSize(new java.awt.Dimension(1200, 1539));

        createCustomerBlueBackground.setBackground(new java.awt.Color(102, 255, 255));

        createCustomerTitle.setFont(new java.awt.Font("Tahoma", 0, 72)); // NOI18N
        createCustomerTitle.setText(" CUSTOMER");

        backButton.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        backButton.setText("BACK");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout createCustomerBlueBackgroundLayout = new javax.swing.GroupLayout(createCustomerBlueBackground);
        createCustomerBlueBackground.setLayout(createCustomerBlueBackgroundLayout);
        createCustomerBlueBackgroundLayout.setHorizontalGroup(
            createCustomerBlueBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, createCustomerBlueBackgroundLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(createCustomerTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 434, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(163, 163, 163)
                .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        createCustomerBlueBackgroundLayout.setVerticalGroup(
            createCustomerBlueBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(createCustomerBlueBackgroundLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(createCustomerBlueBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(backButton)
                    .addComponent(createCustomerTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        addButton.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        addButton.setText("FIND");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        emailLabel.setFont(new java.awt.Font("Tahoma", 0, 40)); // NOI18N
        emailLabel.setText("Email:");

        surnameTextbox.setFont(new java.awt.Font("Tahoma", 0, 40)); // NOI18N

        firstNameLabel.setFont(new java.awt.Font("Tahoma", 0, 40)); // NOI18N
        firstNameLabel.setText("First Name:");

        addressLabel.setFont(new java.awt.Font("Tahoma", 0, 40)); // NOI18N
        addressLabel.setText("Address:");

        dateLabel3.setFont(new java.awt.Font("Tahoma", 0, 40)); // NOI18N
        dateLabel3.setText("Surname:");

        phoneNumberLabel.setFont(new java.awt.Font("Tahoma", 0, 40)); // NOI18N
        phoneNumberLabel.setText("Phone Number:");

        firstNameTextbox.setFont(new java.awt.Font("Tahoma", 0, 40)); // NOI18N

        emailTextbox.setFont(new java.awt.Font("Tahoma", 0, 40)); // NOI18N

        addressTextbox.setFont(new java.awt.Font("Tahoma", 0, 40)); // NOI18N

        phoneNumberTextbox.setFont(new java.awt.Font("Tahoma", 0, 40)); // NOI18N

        addButton1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        addButton1.setText("ADD");
        addButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButton1ActionPerformed(evt);
            }
        });

        addButton2.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        addButton2.setText("UPDATE");
        addButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout createCustomerBackgroundLayout = new javax.swing.GroupLayout(createCustomerBackground);
        createCustomerBackground.setLayout(createCustomerBackgroundLayout);
        createCustomerBackgroundLayout.setHorizontalGroup(
            createCustomerBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(createCustomerBlueBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(createCustomerBackgroundLayout.createSequentialGroup()
                .addGroup(createCustomerBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(createCustomerBackgroundLayout.createSequentialGroup()
                        .addGap(208, 208, 208)
                        .addGroup(createCustomerBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(emailLabel)
                            .addComponent(firstNameLabel)
                            .addGroup(createCustomerBackgroundLayout.createSequentialGroup()
                                .addGroup(createCustomerBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(dateLabel3)
                                    .addComponent(addressLabel)
                                    .addComponent(phoneNumberLabel))
                                .addGap(45, 45, 45)
                                .addGroup(createCustomerBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(phoneNumberTextbox, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(emailTextbox, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(surnameTextbox, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(addressTextbox, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(createCustomerBackgroundLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(addButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(152, Short.MAX_VALUE))
            .addGroup(createCustomerBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, createCustomerBackgroundLayout.createSequentialGroup()
                    .addContainerGap(530, Short.MAX_VALUE)
                    .addComponent(firstNameTextbox, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(151, 151, 151)))
            .addGroup(createCustomerBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, createCustomerBackgroundLayout.createSequentialGroup()
                    .addContainerGap(727, Short.MAX_VALUE)
                    .addComponent(addButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(20, 20, 20)))
        );
        createCustomerBackgroundLayout.setVerticalGroup(
            createCustomerBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(createCustomerBackgroundLayout.createSequentialGroup()
                .addComponent(createCustomerBlueBackground, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65)
                .addComponent(firstNameLabel)
                .addGap(24, 24, 24)
                .addGroup(createCustomerBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dateLabel3)
                    .addComponent(surnameTextbox, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(createCustomerBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addressLabel)
                    .addComponent(addressTextbox, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(createCustomerBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailLabel)
                    .addComponent(emailTextbox, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(createCustomerBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(phoneNumberLabel)
                    .addComponent(phoneNumberTextbox, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addGroup(createCustomerBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addButton)
                    .addComponent(addButton2))
                .addGap(19, 19, 19))
            .addGroup(createCustomerBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(createCustomerBackgroundLayout.createSequentialGroup()
                    .addGap(211, 211, 211)
                    .addComponent(firstNameTextbox, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(431, Short.MAX_VALUE)))
            .addGroup(createCustomerBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, createCustomerBackgroundLayout.createSequentialGroup()
                    .addContainerGap(627, Short.MAX_VALUE)
                    .addComponent(addButton1)
                    .addGap(20, 20, 20)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(createCustomerBackground, javax.swing.GroupLayout.DEFAULT_SIZE, 1099, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(createCustomerBackground, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        // TODO add your handling code here:#
         String sql= "INSERT INTO Customer(ID, firstName, lastName, phoneNum,email, type, discountType, discountRate, address) Values(?,?,?,?,?,?,?,?,?)";
        try (//Get connection to the database
            Connection con = DbCon.getConnection();
            ){
            
           
            //changes made 
          pst=con.prepareStatement(sql);
           pst.setString(1, null);
          pst.setString(3, firstNameTextbox.getText());
          pst.setString(4, surnameTextbox.getText());
         pst.setString(5, phoneNumberTextbox.getText());
         pst.setString(6, emailTextbox.getText());
          pst.setString(7, "regular");
          pst.setString(8, null);
         pst.setString(9, null);
         pst.setString(10, addressTextbox.getText());
        
         
          pst.execute();
          JOptionPane.showMessageDialog(null,"inserted successfully" );
          dispose();
        
        }
        catch (Exception e) {
        JOptionPane.showMessageDialog(null,"error");
        }
    }//GEN-LAST:event_addButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
        dispose(); 
    }//GEN-LAST:event_backButtonActionPerformed

    private void addButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addButton1ActionPerformed

    private void addButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CustomerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CustomerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CustomerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustomerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CustomerForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JButton addButton1;
    private javax.swing.JButton addButton2;
    private javax.swing.JLabel addressLabel;
    private javax.swing.JTextField addressTextbox;
    private javax.swing.JButton backButton;
    private javax.swing.JPanel createCustomerBackground;
    private javax.swing.JPanel createCustomerBlueBackground;
    private javax.swing.JLabel createCustomerTitle;
    private javax.swing.JLabel dateLabel3;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JTextField emailTextbox;
    private javax.swing.JLabel firstNameLabel;
    private javax.swing.JTextField firstNameTextbox;
    private javax.swing.JLabel phoneNumberLabel;
    private javax.swing.JTextField phoneNumberTextbox;
    private javax.swing.JTextField surnameTextbox;
    // End of variables declaration//GEN-END:variables
}
