/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author dhruv
 */
public class CustomerStatus extends javax.swing.JFrame {

    /**
     * Creates new form customerStatus
     */
    public CustomerStatus() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        customerStatusBackground = new javax.swing.JPanel();
        bluePanel = new javax.swing.JPanel();
        customerStatusTitle = new javax.swing.JLabel();
        backButton = new javax.swing.JButton();
        rangeFromLabel = new javax.swing.JLabel();
        rangeToTextbox = new javax.swing.JTextField();
        discountTypeComboBox = new javax.swing.JComboBox<>();
        setStatusComboBox = new javax.swing.JComboBox<>();
        saveButton = new javax.swing.JButton();
        rateLabel1 = new javax.swing.JLabel();
        rangeToLabel = new javax.swing.JLabel();
        rateTextbox1 = new javax.swing.JTextField();
        rangeFromTextbox1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        customerStatusBackground.setBackground(new java.awt.Color(255, 255, 255));
        customerStatusBackground.setPreferredSize(new java.awt.Dimension(1100, 800));

        bluePanel.setBackground(new java.awt.Color(125, 240, 240));

        customerStatusTitle.setFont(new java.awt.Font("Tahoma", 0, 60)); // NOI18N
        customerStatusTitle.setText("CUSTOMER STATUS");

        backButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        backButton.setText("BACK");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonadvisorListActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout bluePanelLayout = new javax.swing.GroupLayout(bluePanel);
        bluePanel.setLayout(bluePanelLayout);
        bluePanelLayout.setHorizontalGroup(
            bluePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bluePanelLayout.createSequentialGroup()
                .addContainerGap(280, Short.MAX_VALUE)
                .addComponent(customerStatusTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 551, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(144, 144, 144)
                .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        bluePanelLayout.setVerticalGroup(
            bluePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bluePanelLayout.createSequentialGroup()
                .addGroup(bluePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bluePanelLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(customerStatusTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(bluePanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(54, Short.MAX_VALUE))
        );

        rangeFromLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        rangeFromLabel.setText("Range From:");

        rangeToTextbox.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        rangeToTextbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rangeToTextboxActionPerformed(evt);
            }
        });

        discountTypeComboBox.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        discountTypeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "DISCOUNT TYPE", "Fixed", "Flexible" }));
        discountTypeComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                discountTypeComboBoxActionPerformed(evt);
            }
        });

        setStatusComboBox.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        setStatusComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SET STATUS", "Regular", "Valued" }));
        setStatusComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setStatusComboBoxActionPerformed(evt);
            }
        });

        saveButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        saveButton.setText("SAVE");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonadvisorListActionPerformed(evt);
            }
        });

        rateLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        rateLabel1.setText("Rate(%):");

        rangeToLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        rangeToLabel.setText(" To:");

        rateTextbox1.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        rateTextbox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rateTextbox1ActionPerformed(evt);
            }
        });

        rangeFromTextbox1.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        rangeFromTextbox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rangeFromTextbox1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout customerStatusBackgroundLayout = new javax.swing.GroupLayout(customerStatusBackground);
        customerStatusBackground.setLayout(customerStatusBackgroundLayout);
        customerStatusBackgroundLayout.setHorizontalGroup(
            customerStatusBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bluePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(customerStatusBackgroundLayout.createSequentialGroup()
                .addGroup(customerStatusBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, customerStatusBackgroundLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(saveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(customerStatusBackgroundLayout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addGroup(customerStatusBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(setStatusComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(discountTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(192, 192, 192)
                        .addGroup(customerStatusBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(customerStatusBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(rangeToLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(rangeFromLabel))
                            .addComponent(rateLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(customerStatusBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rateTextbox1, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rangeToTextbox, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rangeFromTextbox1, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        customerStatusBackgroundLayout.setVerticalGroup(
            customerStatusBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(customerStatusBackgroundLayout.createSequentialGroup()
                .addComponent(bluePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67)
                .addGroup(customerStatusBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(setStatusComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rateLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(customerStatusBackgroundLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(rateTextbox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 157, Short.MAX_VALUE)
                .addGroup(customerStatusBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(customerStatusBackgroundLayout.createSequentialGroup()
                        .addComponent(discountTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(148, 148, 148))
                    .addGroup(customerStatusBackgroundLayout.createSequentialGroup()
                        .addGroup(customerStatusBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rangeFromTextbox1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rangeFromLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(customerStatusBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(rangeToLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rangeToTextbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(121, 121, 121)))
                .addComponent(saveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(customerStatusBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(customerStatusBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonadvisorListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonadvisorListActionPerformed
        // TODO add your handling code here:
         dispose(); 
    }//GEN-LAST:event_backButtonadvisorListActionPerformed

    private void rangeToTextboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rangeToTextboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rangeToTextboxActionPerformed

    private void discountTypeComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_discountTypeComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_discountTypeComboBoxActionPerformed

    private void setStatusComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setStatusComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_setStatusComboBoxActionPerformed

    private void saveButtonadvisorListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonadvisorListActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_saveButtonadvisorListActionPerformed

    private void rateTextbox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rateTextbox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rateTextbox1ActionPerformed

    private void rangeFromTextbox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rangeFromTextbox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rangeFromTextbox1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CustomerStatus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CustomerStatus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CustomerStatus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustomerStatus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CustomerStatus().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JPanel bluePanel;
    private javax.swing.JPanel customerStatusBackground;
    private javax.swing.JLabel customerStatusTitle;
    private javax.swing.JComboBox<String> discountTypeComboBox;
    private javax.swing.JLabel rangeFromLabel;
    private javax.swing.JTextField rangeFromTextbox1;
    private javax.swing.JLabel rangeToLabel;
    private javax.swing.JTextField rangeToTextbox;
    private javax.swing.JLabel rateLabel1;
    private javax.swing.JTextField rateTextbox1;
    private javax.swing.JButton saveButton;
    private javax.swing.JComboBox<String> setStatusComboBox;
    // End of variables declaration//GEN-END:variables
}
