/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author xahna
 */
public class customerInformationPopup extends javax.swing.JFrame {

    /**
     * Creates new form customerInformationPopup
     */
    public customerInformationPopup() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        customerInformationBackground = new javax.swing.JPanel();
        customerInformationBlueBackground = new javax.swing.JPanel();
        customerInformationTitle = new javax.swing.JLabel();
        saveButton = new javax.swing.JButton();
        emailLabel = new javax.swing.JLabel();
        surnameTextbox = new javax.swing.JTextField();
        firstNameLabel = new javax.swing.JLabel();
        addressLabel = new javax.swing.JLabel();
        surnameLabel = new javax.swing.JLabel();
        phoneNumberLabel = new javax.swing.JLabel();
        firstNameTextbox = new javax.swing.JTextField();
        emailTextbox = new javax.swing.JTextField();
        addressTextbox = new javax.swing.JTextField();
        phoneNumberTextbox = new javax.swing.JTextField();
        typeLabel = new javax.swing.JLabel();
        typeTextbox = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        customerInformationBackground.setBackground(new java.awt.Color(255, 255, 255));
        customerInformationBackground.setPreferredSize(new java.awt.Dimension(1200, 1539));

        customerInformationBlueBackground.setBackground(new java.awt.Color(102, 255, 255));

        customerInformationTitle.setFont(new java.awt.Font("Tahoma", 0, 72)); // NOI18N
        customerInformationTitle.setText("CUSTOMER INFORMATION");

        javax.swing.GroupLayout customerInformationBlueBackgroundLayout = new javax.swing.GroupLayout(customerInformationBlueBackground);
        customerInformationBlueBackground.setLayout(customerInformationBlueBackgroundLayout);
        customerInformationBlueBackgroundLayout.setHorizontalGroup(
            customerInformationBlueBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(customerInformationBlueBackgroundLayout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addComponent(customerInformationTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 861, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        customerInformationBlueBackgroundLayout.setVerticalGroup(
            customerInformationBlueBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(customerInformationBlueBackgroundLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(customerInformationTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        saveButton.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        saveButton.setText("SAVE");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        emailLabel.setFont(new java.awt.Font("Tahoma", 0, 40)); // NOI18N
        emailLabel.setText("Email:");

        surnameTextbox.setFont(new java.awt.Font("Tahoma", 0, 40)); // NOI18N

        firstNameLabel.setFont(new java.awt.Font("Tahoma", 0, 40)); // NOI18N
        firstNameLabel.setText("First Name:");

        addressLabel.setFont(new java.awt.Font("Tahoma", 0, 40)); // NOI18N
        addressLabel.setText("Address:");

        surnameLabel.setFont(new java.awt.Font("Tahoma", 0, 40)); // NOI18N
        surnameLabel.setText("Surname:");

        phoneNumberLabel.setFont(new java.awt.Font("Tahoma", 0, 40)); // NOI18N
        phoneNumberLabel.setText("Phone:");

        firstNameTextbox.setFont(new java.awt.Font("Tahoma", 0, 40)); // NOI18N
        firstNameTextbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstNameTextboxActionPerformed(evt);
            }
        });

        emailTextbox.setFont(new java.awt.Font("Tahoma", 0, 40)); // NOI18N

        addressTextbox.setFont(new java.awt.Font("Tahoma", 0, 40)); // NOI18N

        phoneNumberTextbox.setFont(new java.awt.Font("Tahoma", 0, 40)); // NOI18N

        typeLabel.setFont(new java.awt.Font("Tahoma", 0, 40)); // NOI18N
        typeLabel.setText("Type:");

        typeTextbox.setFont(new java.awt.Font("Tahoma", 0, 40)); // NOI18N

        javax.swing.GroupLayout customerInformationBackgroundLayout = new javax.swing.GroupLayout(customerInformationBackground);
        customerInformationBackground.setLayout(customerInformationBackgroundLayout);
        customerInformationBackgroundLayout.setHorizontalGroup(
            customerInformationBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(customerInformationBlueBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(customerInformationBackgroundLayout.createSequentialGroup()
                .addGap(0, 738, Short.MAX_VALUE)
                .addComponent(saveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(customerInformationBackgroundLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(customerInformationBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(customerInformationBackgroundLayout.createSequentialGroup()
                        .addComponent(phoneNumberLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 86, Short.MAX_VALUE)
                        .addComponent(phoneNumberTextbox, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(customerInformationBackgroundLayout.createSequentialGroup()
                        .addComponent(firstNameLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(customerInformationBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(addressTextbox, javax.swing.GroupLayout.DEFAULT_SIZE, 296, Short.MAX_VALUE)
                            .addComponent(firstNameTextbox)))
                    .addComponent(addressLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(customerInformationBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(surnameLabel)
                    .addComponent(emailLabel)
                    .addComponent(typeLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(customerInformationBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(typeTextbox, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emailTextbox, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(surnameTextbox, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        customerInformationBackgroundLayout.setVerticalGroup(
            customerInformationBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(customerInformationBackgroundLayout.createSequentialGroup()
                .addComponent(customerInformationBlueBackground, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(78, 78, 78)
                .addGroup(customerInformationBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(firstNameLabel)
                    .addGroup(customerInformationBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(firstNameTextbox, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(surnameLabel)
                        .addComponent(surnameTextbox, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(104, 104, 104)
                .addGroup(customerInformationBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addressLabel)
                    .addComponent(addressTextbox, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emailLabel)
                    .addComponent(emailTextbox, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(107, 107, 107)
                .addGroup(customerInformationBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(phoneNumberLabel)
                    .addComponent(phoneNumberTextbox, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(typeLabel)
                    .addComponent(typeTextbox, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                .addComponent(saveButton)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(customerInformationBackground, javax.swing.GroupLayout.DEFAULT_SIZE, 1100, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(customerInformationBackground, javax.swing.GroupLayout.DEFAULT_SIZE, 747, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_saveButtonActionPerformed

    private void firstNameTextboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstNameTextboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstNameTextboxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(customerInformationPopup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(customerInformationPopup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(customerInformationPopup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(customerInformationPopup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new customerInformationPopup().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addressLabel;
    private javax.swing.JTextField addressTextbox;
    private javax.swing.JPanel customerInformationBackground;
    private javax.swing.JPanel customerInformationBlueBackground;
    private javax.swing.JLabel customerInformationTitle;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JTextField emailTextbox;
    private javax.swing.JLabel firstNameLabel;
    private javax.swing.JTextField firstNameTextbox;
    private javax.swing.JLabel phoneNumberLabel;
    private javax.swing.JTextField phoneNumberTextbox;
    private javax.swing.JButton saveButton;
    private javax.swing.JLabel surnameLabel;
    private javax.swing.JTextField surnameTextbox;
    private javax.swing.JLabel typeLabel;
    private javax.swing.JTextField typeTextbox;
    // End of variables declaration//GEN-END:variables
}
