
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author xahna
 */
public class ReturnTicket extends javax.swing.JFrame {

    /**
     * Creates new form returnTicket
     */
    public ReturnTicket() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        returnTicketBackground = new javax.swing.JPanel();
        returnTicketBlueBackground = new javax.swing.JPanel();
        bookTicketTitle = new javax.swing.JLabel();
        backButton = new javax.swing.JButton();
        recordReturnLogButton = new javax.swing.JButton();
        ticketIDLabel = new javax.swing.JLabel();
        refundButton = new javax.swing.JButton();
        ticketIDTextbox = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        returnTicketBackground.setBackground(new java.awt.Color(255, 255, 255));
        returnTicketBackground.setPreferredSize(new java.awt.Dimension(1200, 1539));

        returnTicketBlueBackground.setBackground(new java.awt.Color(102, 255, 255));

        bookTicketTitle.setFont(new java.awt.Font("Tahoma", 0, 72)); // NOI18N
        bookTicketTitle.setText("RETURN TICKET");

        backButton.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        backButton.setText("BACK");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout returnTicketBlueBackgroundLayout = new javax.swing.GroupLayout(returnTicketBlueBackground);
        returnTicketBlueBackground.setLayout(returnTicketBlueBackgroundLayout);
        returnTicketBlueBackgroundLayout.setHorizontalGroup(
            returnTicketBlueBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, returnTicketBlueBackgroundLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bookTicketTitle)
                .addGap(147, 147, 147)
                .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        returnTicketBlueBackgroundLayout.setVerticalGroup(
            returnTicketBlueBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(returnTicketBlueBackgroundLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(returnTicketBlueBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(backButton)
                    .addComponent(bookTicketTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        recordReturnLogButton.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        recordReturnLogButton.setText("Record return in log");
        recordReturnLogButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recordReturnLogButtonActionPerformed(evt);
            }
        });

        ticketIDLabel.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        ticketIDLabel.setText("Ticket ID:");

        refundButton.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        refundButton.setText("Refund");
        refundButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refundButtonActionPerformed(evt);
            }
        });

        ticketIDTextbox.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N

        javax.swing.GroupLayout returnTicketBackgroundLayout = new javax.swing.GroupLayout(returnTicketBackground);
        returnTicketBackground.setLayout(returnTicketBackgroundLayout);
        returnTicketBackgroundLayout.setHorizontalGroup(
            returnTicketBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(returnTicketBlueBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(returnTicketBackgroundLayout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(recordReturnLogButton, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(refundButton, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61))
            .addGroup(returnTicketBackgroundLayout.createSequentialGroup()
                .addGap(256, 256, 256)
                .addComponent(ticketIDLabel)
                .addGap(65, 65, 65)
                .addComponent(ticketIDTextbox, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(243, Short.MAX_VALUE))
        );
        returnTicketBackgroundLayout.setVerticalGroup(
            returnTicketBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(returnTicketBackgroundLayout.createSequentialGroup()
                .addComponent(returnTicketBlueBackground, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 237, Short.MAX_VALUE)
                .addGroup(returnTicketBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ticketIDTextbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ticketIDLabel))
                .addGap(259, 259, 259)
                .addGroup(returnTicketBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(recordReturnLogButton)
                    .addComponent(refundButton))
                .addGap(165, 165, 165))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(returnTicketBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(returnTicketBackground, javax.swing.GroupLayout.DEFAULT_SIZE, 901, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_backButtonActionPerformed

    private void recordReturnLogButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recordReturnLogButtonActionPerformed
        // TODO add your handling code here:
        try (Connection con = DbCon.getConnection()) {
            int id = AdvisorHub.id;

            PreparedStatement pst2 = con.prepareStatement("select  name from staff where ID='" + id + "' ");

            ResultSet rs2 = pst2.executeQuery();

            String filename = rs2.getString("name") + " " + "logfile";

            ProcessBuilder pb = new ProcessBuilder("Notepad.exe", filename);
            pb.start();

        } catch (Exception e) {
            System.out.println("error");
        }
    }//GEN-LAST:event_recordReturnLogButtonActionPerformed

    private void refundButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refundButtonActionPerformed
        // TODO add your handling code here:
        String blank = ticketIDTextbox.getText().toString();

        try (Connection con = DbCon.getConnection()) {

            PreparedStatement ps = con.prepareStatement("update Payment set isRefunded = '1' where BlankblankNumber = '" + blank + "'");
            ps.execute();

            PreparedStatement rst = null;
            rst = con.prepareStatement(" DELETE FROM Itinerary WHERE BlankblankNumber='" + blank + "' ");
            rst.execute();

            JOptionPane.showMessageDialog(null, "Ticket returned successfully");

        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(BookTicket.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_refundButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReturnTicket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReturnTicket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReturnTicket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReturnTicket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReturnTicket().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JLabel bookTicketTitle;
    private javax.swing.JButton recordReturnLogButton;
    private javax.swing.JButton refundButton;
    private javax.swing.JPanel returnTicketBackground;
    private javax.swing.JPanel returnTicketBlueBackground;
    private javax.swing.JLabel ticketIDLabel;
    private javax.swing.JTextField ticketIDTextbox;
    // End of variables declaration//GEN-END:variables
}
